### ISSUE TITLE
Padronizar palavra "e-mail" com hífen

### ISSUE THREAD

**Issue by marianeluizac** [impulsoteam/comunidadestech#168]
**Problema:** Em alguns lugares a palavra e-mail aparece sem o hífen. Por exemplo, na tela para se cadastrar uma comunidade, aparece "e-mail" de liderança e depois "Email" de administrador.

**Valor do issue:** Conseguiremos padronizar todo o site.

**Comment by GabisPapin** [comment]
Olá, posso ajudar com essa issue?
Vi que eu preciso criar uma página no linkedin, no caso eu não tenho empresa e não estou trabalhando, mesmo assim posso contribuir?

**Comment by dudunog** [comment]
A issue parece interessante. Também brilha aos meus olhos a correta utilização da palavra em toda a aplicação com foco em padronização. Por isso, criei um PR com a solução disso! #385
