### ISSUE TITLE
Ajustes com base nos indicativos do Lighthouse PWA

### ISSUE THREAD

**Issue by omarciovsena** [impulsoteam/comunidadestech#6]
- [x] Add Splash Screen
- [x] Ajustar Manifest
- [x] Corrigir start_url
- [x] Implementar comportamento offline

**Comment by operfildoluiz** [comment]
nao consigo me assinar WAT

**Comment by operfildoluiz** [comment]
[https://github.com/universoimpulso/comunidadestech/pull/14](https://github.com/universoimpulso/comunidadestech/pull/14)
